services:
  - type: web
    name: movies-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: MONGO_URI
        value: your_mongodb_connection_string
      - key: JWT_SECRET
        value: your_secret_key
    plan: free
